//! Verify a `.crate` against the commit it declares.
//!
//! `cargo publish` repackages from the working tree, so an archive's bytes are
//! a property of the machine that built it -- its platform, its checkout's
//! end-of-line configuration, its Cargo version -- as well as of the commit.
//! Comparing two archives byte for byte therefore fails for correct releases
//! and cannot tell a line-ending difference from edited content.
//!
//! So the comparison is anchored on Git instead. Every packaged source entry is
//! re-derived from the blob Git stores at the declared commit, which is
//! end-of-line normalized on the way in and identical on every platform. A
//! difference that survives normalization is edited content and fails; one that
//! does not is a checkout artifact and passes under its own name.
//!
//! Three entries are generated by Cargo and exist in no commit. They get
//! assertions rather than comparisons -- see [`check_vcs_info`],
//! [`check_manifest_surface`], and [`check_lock_subset`].

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use anyhow::{Context, Result, bail};
use serde::Deserialize;

use crate::archive;
use crate::git;

/// Entries Cargo synthesizes. They exist in no commit, so they are asserted
/// against rather than compared. `Cargo.toml.orig` is deliberately absent: it
/// is a verbatim copy of the crate's manifest and is checked like any source.
const GENERATED: [&str; 3] = [".cargo_vcs_info.json", "Cargo.lock", "Cargo.toml"];

pub struct VerifyRequest<'a> {
    pub repo_root: &'a Path,
    pub archive: &'a Path,
    pub package: &'a str,
    pub version: &'a str,
    /// Where in the repository the crate lives, from `paths.ron`. The archive
    /// declares this too; the two must agree.
    pub expect_path_in_vcs: &'a str,
    /// Revision the archive must have been packaged from. `None` trusts the
    /// archive's own declaration, which establishes far less.
    pub rev: Option<&'a str>,
    /// Authoritative archive checksum, when one is known independently.
    pub expect_sha256: Option<&'a str>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Verdict {
    /// Byte-identical to the commit's blob.
    Identical,
    /// Differs only in carriage returns before newlines.
    EolOnly,
    /// Differs in a way that survives normalization.
    Mismatch,
    /// In the archive, but no such blob at the commit.
    ExtraInArchive,
    /// Tracked at the commit, but absent from the archive.
    MissingFromArchive,
    /// Cargo-generated, and its assertions held.
    GeneratedOk,
    /// Cargo-generated, and an assertion failed.
    GeneratedFailed,
}

impl Verdict {
    pub fn label(self) -> &'static str {
        match self {
            Verdict::Identical => "OK",
            Verdict::EolOnly => "EOL",
            Verdict::Mismatch => "MISMATCH",
            Verdict::ExtraInArchive => "EXTRA",
            Verdict::MissingFromArchive => "MISSING",
            Verdict::GeneratedOk => "GEN",
            Verdict::GeneratedFailed => "GEN-FAIL",
        }
    }
}

pub struct EntryVerdict {
    pub archive_path: String,
    pub verdict: Verdict,
    /// Digest of the bytes as packaged. Platform-dependent for text.
    pub archive_sha: String,
    /// Digest of those bytes normalized. A property of the commit.
    pub content_sha: String,
    pub blob_oid: Option<String>,
}

pub struct VerifyReport {
    pub archive_name: String,
    pub archive_sha256: String,
    pub declared_commit: String,
    pub resolved_commit: String,
    pub path_in_vcs: String,
    pub entries: Vec<EntryVerdict>,
    pub failures: Vec<String>,
}

impl VerifyReport {
    pub fn is_ok(&self) -> bool {
        self.failures.is_empty()
    }

    pub fn count(&self, verdict: Verdict) -> usize {
        self.entries
            .iter()
            .filter(|entry| entry.verdict == verdict)
            .count()
    }

    pub fn source_entries(&self) -> usize {
        self.entries
            .iter()
            .filter(|entry| {
                !matches!(
                    entry.verdict,
                    Verdict::GeneratedOk | Verdict::GeneratedFailed
                )
            })
            .count()
    }

    /// The digest table written into the release evidence. Three columns:
    /// the packaged bytes, the normalized content, and the Git object id.
    /// Two records built from one commit on different platforms agree on the
    /// last two and disagree on the first.
    pub fn digest_table(&self) -> Vec<String> {
        self.entries
            .iter()
            .map(|entry| {
                format!(
                    "{}  {}  {}  {}",
                    entry.archive_sha,
                    entry.content_sha,
                    entry.blob_oid.as_deref().unwrap_or("-".repeat(40).as_str()),
                    entry.archive_path
                )
            })
            .collect()
    }

    pub fn summary_lines(&self) -> Vec<String> {
        vec![
            format!(
                "- Commit declared by `.cargo_vcs_info.json`: `{}`",
                self.declared_commit
            ),
            format!("- Path in VCS: `{}`", self.path_in_vcs),
            format!(
                "- Source entries: {} — {} content-identical to the commit's blobs, {} end-of-line-only, {} mismatched",
                self.source_entries(),
                self.count(Verdict::Identical),
                self.count(Verdict::EolOnly),
                self.count(Verdict::Mismatch),
            ),
            format!(
                "- Tracked at the commit but absent from the archive: {}",
                self.count(Verdict::MissingFromArchive)
            ),
            format!(
                "- In the archive with no blob at the commit: {}",
                self.count(Verdict::ExtraInArchive)
            ),
            format!(
                "- Cargo-generated entries: {} — declared commit, dependency and feature surface, and locked versions all agree with the commit",
                self.count(Verdict::GeneratedOk) + self.count(Verdict::GeneratedFailed)
            ),
        ]
    }
}

#[derive(Deserialize)]
struct VcsInfo {
    git: VcsGit,
    path_in_vcs: Option<String>,
}

#[derive(Deserialize)]
struct VcsGit {
    sha1: String,
    #[serde(default)]
    dirty: Option<bool>,
}

pub fn verify(req: &VerifyRequest) -> Result<VerifyReport> {
    let archive_sha256 = archive::sha256_file(req.archive)?;
    // Check this before reading a single entry. If the bytes are not the
    // artifact they were supposed to be, nothing computed from them is worth
    // reporting.
    if let Some(expected) = req.expect_sha256
        && !expected.eq_ignore_ascii_case(&archive_sha256)
    {
        bail!(
            "{} hashes to {archive_sha256}, not the expected {expected}; this is not the artifact that checksum names",
            req.archive.display()
        );
    }

    let prefix = format!("{}-{}/", req.package, req.version);
    let entries = archive::entries(req.archive, &prefix)?;

    let vcs_raw = entries
        .iter()
        .find(|(name, _)| name == ".cargo_vcs_info.json")
        .map(|(_, data)| data.as_slice())
        .context(
            "the archive holds no .cargo_vcs_info.json, so it names no commit and nothing about it can be verified",
        )?;
    let vcs: VcsInfo =
        serde_json::from_slice(vcs_raw).context("failed to parse .cargo_vcs_info.json")?;

    let mut failures = Vec::new();
    let path_in_vcs = vcs
        .path_in_vcs
        .clone()
        .unwrap_or_else(|| req.expect_path_in_vcs.to_string());

    let resolved_commit = git::rev_parse(req.repo_root, req.rev.unwrap_or(&vcs.git.sha1))?;
    failures.extend(check_vcs_info(
        &vcs,
        &path_in_vcs,
        req.expect_path_in_vcs,
        &resolved_commit,
        req.rev,
    ));

    let tree = git::ls_tree(req.repo_root, &resolved_commit, &path_in_vcs)?;
    let mut expected: BTreeMap<String, String> = BTreeMap::new();
    for (oid, path) in tree {
        let rel = path
            .strip_prefix(&format!("{path_in_vcs}/"))
            .unwrap_or(path.as_str());
        expected.insert(archive_name_for(rel), oid);
    }

    let mut seen = BTreeSet::new();
    let mut verdicts = Vec::new();
    for (name, data) in &entries {
        seen.insert(name.clone());
        let archive_sha = archive::sha256_hex(data);
        let content_sha = archive::content_digest(data);

        if GENERATED.contains(&name.as_str()) {
            let notes = check_generated(req, name, data, &resolved_commit, &path_in_vcs)?;
            let failed = !notes.is_empty();
            for note in &notes {
                failures.push(format!("{name}: {note}"));
            }
            verdicts.push(EntryVerdict {
                archive_path: name.clone(),
                verdict: if failed {
                    Verdict::GeneratedFailed
                } else {
                    Verdict::GeneratedOk
                },
                archive_sha,
                content_sha,
                blob_oid: None,
            });
            continue;
        }

        let Some(oid) = expected.get(name) else {
            failures.push(format!(
                "{name}: present in the archive but tracked at no path under {path_in_vcs} at {resolved_commit}"
            ));
            verdicts.push(EntryVerdict {
                archive_path: name.clone(),
                verdict: Verdict::ExtraInArchive,
                archive_sha,
                content_sha,
                blob_oid: None,
            });
            continue;
        };

        let git_path = format!("{path_in_vcs}/{}", git_name_for(name));
        let blob = git::blob(req.repo_root, &resolved_commit, &git_path)?;
        let verdict = compare(data, &blob);
        if verdict == Verdict::Mismatch {
            failures.push(format!(
                "{name}: content differs from {git_path} at {resolved_commit}"
            ));
        }
        verdicts.push(EntryVerdict {
            archive_path: name.clone(),
            verdict,
            archive_sha,
            content_sha,
            blob_oid: Some(oid.clone()),
        });
    }

    for (name, oid) in &expected {
        if seen.contains(name) {
            continue;
        }
        failures.push(format!(
            "{name}: tracked at {resolved_commit} but absent from the archive"
        ));
        verdicts.push(EntryVerdict {
            archive_path: name.clone(),
            verdict: Verdict::MissingFromArchive,
            archive_sha: String::from("-"),
            content_sha: String::from("-"),
            blob_oid: Some(oid.clone()),
        });
    }

    verdicts.sort_by(|a, b| a.archive_path.cmp(&b.archive_path));

    Ok(VerifyReport {
        archive_name: req
            .archive
            .file_name()
            .map(|name| name.to_string_lossy().into_owned())
            .unwrap_or_default(),
        archive_sha256,
        declared_commit: vcs.git.sha1.clone(),
        resolved_commit,
        path_in_vcs,
        entries: verdicts,
        failures,
    })
}

/// Compare a packaged entry against the commit's blob. Both sides are
/// normalized: the blob side is LF today, but a future `-text` attribute would
/// change that, and normalizing only one side would be a silent asymmetry.
pub fn compare(archive_bytes: &[u8], blob: &[u8]) -> Verdict {
    if archive_bytes == blob {
        return Verdict::Identical;
    }
    // Normalizing a binary is not sound: there, a CR before an LF is data.
    if archive::looks_textual(archive_bytes)
        && archive::looks_textual(blob)
        && archive::normalize_lf(archive_bytes) == archive::normalize_lf(blob)
    {
        return Verdict::EolOnly;
    }
    Verdict::Mismatch
}

/// Cargo renames the crate's own manifest when packaging; every other entry
/// keeps its path. These two are inverses.
pub fn archive_name_for(git_relative: &str) -> String {
    if git_relative == "Cargo.toml" {
        String::from("Cargo.toml.orig")
    } else {
        git_relative.to_string()
    }
}

pub fn git_name_for(archive_relative: &str) -> String {
    if archive_relative == "Cargo.toml.orig" {
        String::from("Cargo.toml")
    } else {
        archive_relative.to_string()
    }
}

fn check_vcs_info(
    vcs: &VcsInfo,
    path_in_vcs: &str,
    expect_path_in_vcs: &str,
    resolved_commit: &str,
    rev: Option<&str>,
) -> Vec<String> {
    let mut failures = Vec::new();
    if vcs.git.dirty == Some(true) {
        failures.push(String::from(
            ".cargo_vcs_info.json: packaged from a dirty tree, so it describes no commit",
        ));
    }
    if path_in_vcs != expect_path_in_vcs {
        failures.push(format!(
            ".cargo_vcs_info.json: declares path_in_vcs {path_in_vcs}, but this repository packages the driver from {expect_path_in_vcs}"
        ));
    }
    // Only meaningful when the caller named a revision. Without one the
    // resolved commit came from this same field and agreement is circular.
    if rev.is_some() && vcs.git.sha1 != resolved_commit {
        failures.push(format!(
            ".cargo_vcs_info.json: declares commit {}, but the requested revision resolves to {resolved_commit}",
            vcs.git.sha1
        ));
    }
    failures
}

fn check_generated(
    req: &VerifyRequest,
    name: &str,
    data: &[u8],
    commit: &str,
    path_in_vcs: &str,
) -> Result<Vec<String>> {
    match name {
        // Already asserted in check_vcs_info, before the entry loop.
        ".cargo_vcs_info.json" => Ok(Vec::new()),
        "Cargo.toml" => {
            let normalized = String::from_utf8_lossy(data).into_owned();
            let source = git::blob(req.repo_root, commit, &format!("{path_in_vcs}/Cargo.toml"))?;
            let workspace = git::blob(req.repo_root, commit, "Cargo.toml")?;
            Ok(check_manifest_surface(
                &normalized,
                &String::from_utf8_lossy(&source),
                &String::from_utf8_lossy(&workspace),
                req.package,
                req.version,
            ))
        }
        "Cargo.lock" => {
            let packaged = String::from_utf8_lossy(data).into_owned();
            let root = git::blob(req.repo_root, commit, "Cargo.lock")?;
            Ok(check_lock_subset(
                &packaged,
                &String::from_utf8_lossy(&root),
                req.package,
                req.version,
            ))
        }
        other => Ok(vec![format!("unhandled generated entry {other}")]),
    }
}

/// Keys the driver manifest inherits from `[workspace.package]`. Resolving
/// only these is deliberate: a general inheritance resolver would be far more
/// code for no additional coverage.
const INHERITED: [&str; 6] = [
    "version",
    "authors",
    "edition",
    "license",
    "repository",
    "rust-version",
];

/// The normalized manifest cannot be reproduced byte for byte without pinning
/// the publishing Cargo version, so assert its meaning instead.
///
/// This check is load-bearing rather than decorative. Every other check in
/// this module looks at source entries and the entry set, and a dependency
/// added to the normalized manifest alone disturbs neither -- the archive
/// would ship a dependency that exists in no commit and still verify.
pub fn check_manifest_surface(
    normalized: &str,
    source: &str,
    workspace: &str,
    package: &str,
    version: &str,
) -> Vec<String> {
    let mut failures = Vec::new();
    let (normalized, source, workspace) = match (
        normalized.parse::<toml::Value>(),
        source.parse::<toml::Value>(),
        workspace.parse::<toml::Value>(),
    ) {
        (Ok(n), Ok(s), Ok(w)) => (n, s, w),
        _ => return vec![String::from("could not parse one of the manifests as TOML")],
    };

    let normalized_pkg = normalized.get("package");
    if normalized_pkg
        .and_then(|p| p.get("name"))
        .and_then(toml::Value::as_str)
        != Some(package)
    {
        failures.push(format!("package.name is not {package}"));
    }
    if normalized_pkg
        .and_then(|p| p.get("version"))
        .and_then(toml::Value::as_str)
        != Some(version)
    {
        failures.push(format!("package.version is not {version}"));
    }

    let source_pkg = source.get("package");
    let workspace_pkg = workspace.get("workspace").and_then(|w| w.get("package"));
    for key in INHERITED {
        let Some(declared) = source_pkg.and_then(|p| p.get(key)) else {
            continue;
        };
        // `key.workspace = true` means the real value lives in the root.
        let expected = if declared
            .get("workspace")
            .and_then(toml::Value::as_bool)
            .unwrap_or(false)
        {
            workspace_pkg.and_then(|p| p.get(key))
        } else {
            Some(declared)
        };
        let Some(expected) = expected else {
            failures.push(format!(
                "package.{key} is declared at the commit but resolves to nothing; the workspace root does not define it"
            ));
            continue;
        };
        // A key the commit declares and the archive omits is a loss of
        // metadata, not an absence of evidence.
        let Some(actual) = normalized_pkg.and_then(|p| p.get(key)) else {
            failures.push(format!(
                "package.{key} is absent from the archive, but the commit's manifests declare {expected}"
            ));
            continue;
        };
        if expected != actual {
            failures.push(format!(
                "package.{key} is {actual}, but the commit's manifests resolve it to {expected}"
            ));
        }
    }

    for key in [
        "description",
        "homepage",
        "documentation",
        "readme",
        "keywords",
        "categories",
    ] {
        // Only keys the commit declares: Cargo synthesizes others (`build`,
        // `autolib`, the `auto*` family) that appear in no source manifest.
        let Some(expected) = source_pkg.and_then(|p| p.get(key)) else {
            continue;
        };
        match normalized_pkg.and_then(|p| p.get(key)) {
            None => failures.push(format!(
                "package.{key} is absent from the archive, but the commit's manifest declares it"
            )),
            Some(actual) if actual != expected => {
                failures.push(format!("package.{key} differs from the commit's manifest"))
            }
            Some(_) => {}
        }
    }

    // Every dependency table, including the target-specific ones. A
    // `[target.'cfg(...)'.dependencies]` entry reaches a consumer's build
    // exactly as `[dependencies]` does, and a packaged lock written before
    // such an edit still matches the commit's lock, so nothing else here
    // would see it.
    let normalized_tables = dependency_tables(&normalized);
    let source_tables = dependency_tables(&source);
    let empty = toml::value::Table::new();
    let labels: BTreeSet<&String> = normalized_tables
        .keys()
        .chain(source_tables.keys())
        .collect();
    for label in labels {
        failures.extend(compare_dependency_table(
            normalized_tables.get(label).copied().unwrap_or(&empty),
            source_tables.get(label).copied().unwrap_or(&empty),
            label,
        ));
    }

    let normalized_features = normalized.get("features");
    let source_features = source.get("features");
    if normalized_features != source_features {
        failures.push(String::from(
            "the [features] table differs from the commit's manifest",
        ));
    }

    failures
}

const DEP_TABLES: [&str; 3] = ["dependencies", "dev-dependencies", "build-dependencies"];

/// Every dependency table in a manifest, labelled by where it came from, so
/// `[target.'cfg(unix)'.dependencies]` is compared as carefully as
/// `[dependencies]`.
fn dependency_tables(value: &toml::Value) -> BTreeMap<String, &toml::value::Table> {
    let mut out = BTreeMap::new();
    for table in DEP_TABLES {
        if let Some(found) = value.get(table).and_then(toml::Value::as_table) {
            out.insert(table.to_string(), found);
        }
    }
    if let Some(targets) = value.get("target").and_then(toml::Value::as_table) {
        for (cfg, spec) in targets {
            for table in DEP_TABLES {
                if let Some(found) = spec.get(table).and_then(toml::Value::as_table) {
                    out.insert(format!("target.{cfg}.{table}"), found);
                }
            }
        }
    }
    out
}

/// The keys a dependency declaration carries. A bare version string is the
/// shorthand for a table holding only `version`.
fn dependency_keys(value: &toml::Value) -> BTreeSet<String> {
    match value {
        toml::Value::String(_) => BTreeSet::from([String::from("version")]),
        toml::Value::Table(table) => table.keys().cloned().collect(),
        _ => BTreeSet::new(),
    }
}

/// Cargo rewrites inline dependency tables into `[dependencies.<name>]`
/// sections, so this compares parsed values and never text.
fn compare_dependency_table(
    normalized: &toml::value::Table,
    source: &toml::value::Table,
    table: &str,
) -> Vec<String> {
    let normalized_names: BTreeSet<_> = normalized.keys().cloned().collect();
    let source_names: BTreeSet<_> = source.keys().cloned().collect();
    let mut failures = Vec::new();
    for added in normalized_names.difference(&source_names) {
        failures.push(format!(
            "[{table}] holds {added}, which the commit's manifest does not declare"
        ));
    }
    for removed in source_names.difference(&normalized_names) {
        failures.push(format!(
            "[{table}] omits {removed}, which the commit's manifest declares"
        ));
    }

    for name in normalized_names.intersection(&source_names) {
        let left = &normalized[name];
        let right = &source[name];
        // Compare the union of the keys either side declares, rather than a
        // fixed list. `package` redirects a dependency to a different crate
        // under the same alias, and `git`, `registry`, and `path` all change
        // where the code comes from; enumerating fields would keep missing
        // whichever one was not thought of.
        let mut fields = dependency_keys(left);
        fields.extend(dependency_keys(right));
        for field in fields {
            if field_of(left, &field) != field_of(right, &field) {
                failures.push(format!(
                    "[{table}.{name}] {field} differs from the commit's manifest"
                ));
            }
        }
    }
    failures
}

/// A dependency is either a bare version string or a table. Normalize both to
/// the same shape before comparing a field.
fn field_of(value: &toml::Value, field: &str) -> Option<toml::Value> {
    match value {
        toml::Value::String(_) if field == "version" => Some(value.clone()),
        toml::Value::String(_) => None,
        other => other.get(field).cloned(),
    }
}

/// The packaged lock is a subset of the workspace lock by construction, so any
/// pair it holds that the commit's lock does not is a changed dependency.
pub fn check_lock_subset(packaged: &str, root: &str, package: &str, version: &str) -> Vec<String> {
    let (Ok(packaged), Ok(root)) = (packaged.parse::<toml::Value>(), root.parse::<toml::Value>())
    else {
        return vec![String::from(
            "could not parse one of the lock files as TOML",
        )];
    };
    let pairs = |value: &toml::Value| -> BTreeSet<(String, String)> {
        value
            .get("package")
            .and_then(toml::Value::as_array)
            .map(|items| {
                items
                    .iter()
                    .filter_map(|item| {
                        Some((
                            item.get("name")?.as_str()?.to_string(),
                            item.get("version")?.as_str()?.to_string(),
                        ))
                    })
                    .collect()
            })
            .unwrap_or_default()
    };

    let packaged_pairs = pairs(&packaged);
    let root_pairs = pairs(&root);
    let mut failures = Vec::new();
    if !packaged_pairs.contains(&(package.to_string(), version.to_string())) {
        failures.push(format!("does not pin {package} at {version}"));
    }
    for (name, pinned) in &packaged_pairs {
        if name == package {
            continue;
        }
        if !root_pairs.contains(&(name.clone(), pinned.clone())) {
            failures.push(format!(
                "pins {name} {pinned}, which the commit's Cargo.lock does not"
            ));
        }
    }
    failures
}

#[cfg(test)]
mod tests {
    use super::{
        Verdict, archive_name_for, check_lock_subset, check_manifest_surface, compare, git_name_for,
    };

    const SOURCE: &str = r#"
[package]
name = "demo"
version.workspace = true
description = "a demo"

[dependencies]
embedded-hal-async = { version = "1.0.0", default-features = false }

[features]
default = []
"#;

    const WORKSPACE: &str = r#"
[workspace.package]
version = "0.1.0-incubating.1"
"#;

    const NORMALIZED: &str = r#"
[package]
name = "demo"
version = "0.1.0-incubating.1"
description = "a demo"

[features]
default = []

[dependencies.embedded-hal-async]
version = "1.0.0"
default-features = false
"#;

    // Reported by Codex on #94. Each of the three is an edit that reaches a
    // consumer's build and that the surrounding checks cannot see: the source
    // entries are untouched, the entry set is unchanged, and a packaged lock
    // written before the edit still matches the commit's lock.

    #[test]
    fn manifest_surface_detects_an_injected_target_dependency() {
        let tampered = format!(
            "{NORMALIZED}\n[target.\"cfg(all())\".dependencies.backdoor]\nversion = \"1.0\"\n"
        );
        let failures =
            check_manifest_surface(&tampered, SOURCE, WORKSPACE, "demo", "0.1.0-incubating.1");
        assert!(
            failures.iter().any(|f| f.contains("backdoor")),
            "{failures:?}"
        );
    }

    #[test]
    fn manifest_surface_detects_a_redirected_dependency() {
        let tampered = NORMALIZED.replace(
            "[dependencies.embedded-hal-async]\nversion = \"1.0.0\"",
            "[dependencies.embedded-hal-async]\npackage = \"impostor\"\nversion = \"1.0.0\"",
        );
        let failures =
            check_manifest_surface(&tampered, SOURCE, WORKSPACE, "demo", "0.1.0-incubating.1");
        assert!(
            failures.iter().any(|f| f.contains("package")),
            "{failures:?}"
        );
    }

    #[test]
    fn manifest_surface_detects_dropped_inherited_metadata() {
        let source = format!("{SOURCE}\n[package.extra]\n");
        let source = source.replace(
            "version.workspace = true",
            "version.workspace = true\nlicense.workspace = true",
        );
        let workspace = format!("{WORKSPACE}license = \"MIT\"\n");
        // The normalized manifest simply omits the licence the commit declares.
        let failures = check_manifest_surface(
            NORMALIZED,
            &source,
            &workspace,
            "demo",
            "0.1.0-incubating.1",
        );
        assert!(
            failures.iter().any(|f| f.contains("license")),
            "{failures:?}"
        );
    }

    #[test]
    fn manifest_surface_detects_dropped_descriptive_metadata() {
        let tampered = NORMALIZED.replace("description = \"a demo\"\n", "");
        let failures =
            check_manifest_surface(&tampered, SOURCE, WORKSPACE, "demo", "0.1.0-incubating.1");
        assert!(
            failures.iter().any(|f| f.contains("description")),
            "{failures:?}"
        );
    }

    #[test]
    fn maps_the_manifest_between_its_two_names() {
        assert_eq!(archive_name_for("Cargo.toml"), "Cargo.toml.orig");
        assert_eq!(git_name_for("Cargo.toml.orig"), "Cargo.toml");
        assert_eq!(archive_name_for("src/lib.rs"), "src/lib.rs");
        assert_eq!(git_name_for("src/lib.rs"), "src/lib.rs");
    }

    #[test]
    fn equal_bytes_are_identical() {
        assert_eq!(compare(b"a\nb\n", b"a\nb\n"), Verdict::Identical);
    }

    #[test]
    fn a_crlf_checkout_is_an_end_of_line_difference() {
        assert_eq!(compare(b"a\r\nb\r\n", b"a\nb\n"), Verdict::EolOnly);
    }

    #[test]
    fn normalization_does_not_mask_an_edit() {
        assert_eq!(compare(b"a\r\nc\r\n", b"a\nb\n"), Verdict::Mismatch);
    }

    #[test]
    fn a_binary_entry_is_never_normalized() {
        assert_eq!(compare(b"\0a\r\n", b"\0a\n"), Verdict::Mismatch);
    }

    #[test]
    fn manifest_surface_accepts_the_normalized_form() {
        let failures =
            check_manifest_surface(NORMALIZED, SOURCE, WORKSPACE, "demo", "0.1.0-incubating.1");
        assert!(failures.is_empty(), "{failures:?}");
    }

    #[test]
    fn manifest_surface_detects_an_added_dependency() {
        let tampered = format!("{NORMALIZED}\n[dependencies.backdoor]\nversion = \"1.0\"\n");
        let failures =
            check_manifest_surface(&tampered, SOURCE, WORKSPACE, "demo", "0.1.0-incubating.1");
        assert!(
            failures.iter().any(|f| f.contains("backdoor")),
            "{failures:?}"
        );
    }

    #[test]
    fn manifest_surface_detects_a_changed_version_requirement() {
        let tampered = NORMALIZED.replace("version = \"1.0.0\"", "version = \"9.9.9\"");
        let failures =
            check_manifest_surface(&tampered, SOURCE, WORKSPACE, "demo", "0.1.0-incubating.1");
        assert!(
            failures.iter().any(|f| f.contains("embedded-hal-async")),
            "{failures:?}"
        );
    }

    #[test]
    fn manifest_surface_detects_an_uninherited_version() {
        let tampered = NORMALIZED.replace("0.1.0-incubating.1", "0.2.0-incubating.1");
        let failures =
            check_manifest_surface(&tampered, SOURCE, WORKSPACE, "demo", "0.1.0-incubating.1");
        assert!(!failures.is_empty());
    }

    const PACKAGED_LOCK: &str = r#"
[[package]]
name = "demo"
version = "0.1.0-incubating.1"

[[package]]
name = "embedded-hal-async"
version = "1.0.0"
"#;

    const ROOT_LOCK: &str = r#"
[[package]]
name = "demo"
version = "0.1.0-incubating.1"

[[package]]
name = "embedded-hal-async"
version = "1.0.0"

[[package]]
name = "extra-dev-only"
version = "0.3.0"
"#;

    #[test]
    fn lock_subset_accepts_a_subset_of_the_workspace_lock() {
        let failures = check_lock_subset(PACKAGED_LOCK, ROOT_LOCK, "demo", "0.1.0-incubating.1");
        assert!(failures.is_empty(), "{failures:?}");
    }

    #[test]
    fn lock_subset_detects_a_bumped_dependency() {
        let tampered = PACKAGED_LOCK.replace("1.0.0", "1.0.1");
        let failures = check_lock_subset(&tampered, ROOT_LOCK, "demo", "0.1.0-incubating.1");
        assert!(
            failures.iter().any(|f| f.contains("embedded-hal-async")),
            "{failures:?}"
        );
    }

    #[test]
    fn lock_subset_requires_the_driver_at_the_expected_version() {
        let failures = check_lock_subset(PACKAGED_LOCK, ROOT_LOCK, "demo", "0.9.9-incubating.1");
        assert!(
            failures.iter().any(|f| f.contains("does not pin")),
            "{failures:?}"
        );
    }
}
